### ISSUE TITLE
Function dump_yaml sometimes converted string values to number values, causing invalid CFN templates

### ISSUE THREAD

**Issue by canhnt** [boroivanov/cfn-tools#1]
## Description

When parsing YAML files containing string scalar longer  than 8 chars and start with `0`, the function `dump_yaml` strips single (and double) quotes, which converts string scalar to number scalar. When  CFN templates refers these string values in `Ref` or `Sub` functions, it causes template error.

## Use-case `'012345678'`
Reproduction script:
```
import cfn_tools
content = "Parameters:\n  MyAccountId:\n    Type: String\n    Default: '012345678'"
body = cfn_tools.load_yaml(content)
template_body = cfn_tools.dump_yaml(body)
print template_body
```

### Expected output: 
```
Parameters:
  MyAccountId:
    Type: String
    Default: '012345678'
```

### Actual output:
```
Parameters:
  MyAccountId:
    Type: String
    Default: 012345678
```

## Use-case `'01234567'`
```
import cfn_tools
content = "Parameters:\n  MyAccountId:\n    Type: String\n    Default: '01234567'"
body = cfn_tools.load_yaml(content)
template_body = cfn_tools.dump_yaml(body)
print template_body
```

Output:
```
Parameters:
  MyAccountId:
    Type: String
    Default: '01234567'
```
